

---
version: 1.0.0
recipes:
- link: recipes/SMS-EMAIL.md
  title: MFA with SMS/EMAIL
  type: recipe
- link: recipes/TOTP.md
  title: MFA with TOTP
  type: recipe
- link: recipes/FIDO2.md
  title: MFA with FIDO2
  type: recipe

