################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
- sections:
  - title: Getting Started
    link: docs/getting-started.md
- sections:
  - title: CIAM MFA
    link: docs/getting-started-mfa.md
    sections:
       - link: docs/ciam-mfa/SMS-EMAIL.md
         title: MFA using SMS/EMAIL
         type: recipe
       - title: MFA using TOTP 
         link: docs/ciam-mfa/TOTP.md
         sections:
          - title: TOTP Device Registration 
            link: docs/ciam-mfa/TOTP-Registration.md
            type: recipe
          - title: Authentication using TOTP device
            link: docs/ciam-mfa/TOTP-Authentication.md
            type: recipe
       - link: docs/ciam-mfa/yubikey.md
         title: MFA using Yubikey 
         sections:
          - title: Yubikey Device registration 
            link: docs/ciam-mfa/yubikey-pairing.md
            type: recipe
          - title: Authentication using YubiKey
            link: docs/ciam-mfa/yubikey-authentication.md
            type: recipe
  - title: CIAM Provisioning API
    link: docs/ciam-provisioning/getting-started-provisioning-api.md
    sections:
        - title: Generate Access Token
          link: docs/ciam-provisioning/oauth-token-generation.md
        - title: Application Onboarding
          link: docs/ciam-provisioning/Application/application-setup.md
        - title: Application OAuth Client
          sections:
            - title: Read Application OAuth Client Settings
              link: docs/ciam-provisioning/Application/application-oauth-client/get-oauth-client.md
            - title: Update Application OAuth Client Settings
              link: docs/ciam-provisioning/Application/application-oauth-client/update-oauth-client.md
        - title: Application Token Mapping
          sections:
            - title: Read Application OAuth Client Access Token Settings
              link: docs/ciam-provisioning/Application/application-token-mapping/get-application-token.md
            - title: Customize Application OAuth Client Access Token Settings
              link: docs/ciam-provisioning/Application/application-token-mapping/update-application-token.md
            - title: Reset Application OAuth Client Access Token Settings
              link: docs/ciam-provisioning/Application/application-token-mapping/delete-application-token.md
        - title: Domain
          sections:
            - title: Search Domain
              link: docs/ciam-provisioning/Domain/search-domains.md
            - title: Create Domain
              link: docs/ciam-provisioning/Domain/create-domain.md
            - title: Get Domain by Id
              link: docs/ciam-provisioning/Domain/search-doamin-by-Id.md
            - title: Update Domain
              link: docs/ciam-provisioning/Domain/update-domain.md
            - title: Delete Domain
              link: docs/ciam-provisioning/Domain/delete-domain.md
        - title: Domain User
          sections:
            - title: Search All Domain Users
              link: docs/ciam-provisioning/Domain/User/search-users.md
            - title: Create User
              link: docs/ciam-provisioning/Domain/User/create-user.md
            - title: Get User By Id
              link: docs/ciam-provisioning/Domain/User/search-user-by-Id.md
            - title: Update User
              link: docs/ciam-provisioning/Domain/User/update-user.md
            - title: Delete User
              link: docs/ciam-provisioning/Domain/User/delete-user.md
        - title: Domain Service Account
          sections:
            - title: Search All Domain Service Accounts
              link: docs/ciam-provisioning/Domain/service-account/search-service-accounts.md
            - title: Create User
              link: docs/ciam-provisioning/Domain/service-account/create-service-account.md
            - title: Get User By Id
              link: docs/ciam-provisioning/Domain/service-account/search-service-account-by-Id.md
            - title: Update User
              link: docs/ciam-provisioning/Domain/service-account/update-service-account.md
            - title: Delete User
              link: docs/ciam-provisioning/Domain/service-account/delete-service-account.md

